### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by mathsalmi** [docker/compose-ecs#7]
I'm sorry if this is the wrong place of asking this but I couldn't find much information on Docker Compose docs.

Is this the new production-ready binary that we should be using from now on?

Thanks!

**Comment by austindrenski** [comment]
Hi, at risk of bump commenting, I wanted to add some context that many of us took the very public announcements of collaboration between the Docker, Azure, and AWS teams as a reasonable signal of longevity for the [Docker Compose Cloud Integrations](https://github.com/docker/compose-cli) project.

My organization took a chance on these features, and we've enjoyed using them. It will be disappointing to see them go away, but we accept that's the nature of the work, and are grateful for all the effort the @docker team has put into these tools over the years.

We recognize that this was always an experimental feature, and the @docker team does not owe us continued development time towards it, but the lack of clear, public communication around the deprecation notice is incredibly disappointing.

It would be greatly appreciated if someone from @docker could provide some form of official comment on the deprecation notice that was added to the CLI (docker/compose-cli#2245) almost 3 weeks ago, as well as the ambiguous passing reference to this project as a possible alternative.

**Comment by hyu** [comment]
Hi @austindrenski, 

Speaking as the PM on the Compose team, I appreciate your thoughtful message, and apologize for my delay in response. We're happy that there are people who have found this Cloud Integration useful, and taken a chance on it for their team's workflows.

Our decision to retire this project was not made lightly, and is the result of many different factors ranging from business to technical, such as incomplete support for the full richness of ECS/ACI features within the Compose model. And, to be honest, our investment in this feature has been very minimal as of late, and so we added the explicit retirement messaging to at least communicate this reality (e.g., for those evaluating adoption).

That said, you're right that the deprecation notice leaves much ambiguity still. We tried to say what we could while still working out the fate of the ECS project, as we're uncertain what support we'll have from partners for ongoing maintenance. At present, our plan is to at least make this code available as a reference.

**Comment by nicholastulach** [comment]
Are there alternatives that people are turning to in order to solve these same types of consistent development problems?

**Comment by thorfi** [comment]
> Are there alternatives that people are turning to in order to solve these same types of consistent development problems?

I'm about to start trying this:

https://github.com/compose-x/ecs_composex/

**Comment by austindrenski** [comment]
This tooling is just too useful to give up on, so going to try to answer @mathsalmi question myself by addressing some outstanding issues from here and [docker/compose-cli](https://github.com/docker/compose-cli).

@hyu @ndeloof Can you give us any sense of what Docker (corporate) has in mind for this? Is there anyone internally staffed as a maintainer for this project that we can coordinate with to start landing some community contributions?

- #11
- #20
- #21

**Comment by ndeloof** [comment]
@austindrenski This codebase was extracted for community adoption but we don't have plan to make this an official Docker product, and it should move to a distinct github org as soon as some maintainers propose to adopt it.

I'll update the README to clarify this status
